//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFamilyMapOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMOcontact
    {
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string AgencyName { get; set; }
        public string Addr { get; set; }
        public string City { get; set; }
        public string States { get; set; }
        public string DirFname { get; set; }
        public string DirLame { get; set; }
        public string DirPhone { get; set; }
        public string DirEmail { get; set; }
        public Nullable<int> NumOfSites { get; set; }
        public Nullable<int> ProgramType { get; set; }
        public Nullable<int> NumOfPrenatalChild { get; set; }
        public Nullable<int> NumOfInfantChild { get; set; }
        public Nullable<int> NumOfPreschoolChild { get; set; }
        public Nullable<int> BetterBeginingRated { get; set; }
        public Nullable<int> BB_Level { get; set; }
        public Nullable<int> Interested { get; set; }
        public int ID { get; set; }
        public Nullable<int> ContactNum { get; set; }
    }
}
